---
- name: learning loops
  hosts:  uk
  become: yes
  tasks:

  - name: uninstall "{{ item }}" packages
    yum:
      name: "{{ item }}"
      state: absent
    loop:
      - tree
      - httpd
...